language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository

script:
    - ./gradlew test

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle%
